<a href="https://colab.research.google.com/github/VidushiSharma31/ML-DL/blob/main/Deep%20Learning/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iris Classification with a Neural Network

This notebook demonstrates how to build and train a simple neural network using TensorFlow and Keras to classify the Iris dataset.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score

## Data Loading and Preprocessing

This section loads the Iris dataset and performs necessary preprocessing steps, including splitting the data into training and testing sets and scaling the features.

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = Sequential([Dense(25, activation='relu'),
                    Dense(15, activation='relu'),
                    Dense(3, activation='linear')])

## Model Definition and Training

Here, we define the architecture of the neural network using Keras's Sequential API, compile the model with an optimizer and loss function, and train it on the preprocessed training data.

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [ ]:
model.fit(X_train_scaled, y_train, epochs = 100, verbose=0)

## Model Evaluation

This section evaluates the trained model's performance on the test set and prints the accuracy.

In [ ]:
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

Test Accuracy: 100.00%


## Prediction on Sample Data

Finally, we use the trained model to make predictions on a few sample data points from the test set and compare the predicted classes with the true labels.

In [ ]:
logits = model.predict(X_test_scaled[:5])
preds = tf.nn.softmax(logits)
print("\nPredicted probabilities (first 5 samples):")
print(preds.numpy())
print("\nPredicted classes:", np.argmax(preds, axis=1))
print("True labels:      ", y_test[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

Predicted probabilities (first 5 samples):
[[1.2683860e-02 9.2682350e-01 6.0492657e-02]
 [9.9461597e-01 4.9024876e-03 4.8151531e-04]
 [1.9529312e-05 2.3069569e-04 9.9974972e-01]
 [2.0689946e-02 7.6215535e-01 2.1715476e-01]
 [1.4267525e-02 8.1427836e-01 1.7145413e-01]]

Predicted classes: [1 0 2 1 1]
True labels:       [1 0 2 1 1]
